const products = [
  {
    _id: '1',
    name: 'BoAt AIRDOPES 121v2 TWS Earbuds',
    image: '/images/airdopes-121-v2-black.png',
    descriptions:
    'Plug into your sound with boAt Airdopes 121v2 True Wireless earbuds to enjoy your playlist in a truly wireless way. With Bluetooth v5.0 and Insta wake n pair technology you just have to take out earbuds from the case and they automatically pair with your device in an instant. Its 380mAh carry cum charging case offers an additional playtime of up to 10.5 hours. With a battery capacity of 380mAh for each earbud, indulge in blissful audio experience for up to 3.5 hours per charge. The TWS Airdopes 121v2 comes equipped with 8mm drivers that pump out immersive sound. The stereo calling feature lets the user indulge in smooth and clear chats over calls. One can access the instant voice assistant by just a single press via the Multifunction Button control. It comes in three stylish colours: Active Black, Midnight Blue and Cherry Blossom to uplift the vibes like never before.',
    brand: 'boAt',
    category: 'Electronics',
    price: 26.99,
    countInStock: 10,
    rating: 4.7,
    numReviews: 262,
  },
    {
    _id: '2',
    name: 'MICROMAX IN 1b (purple, 32 GB',
    image: '/images/micromax-in-1b.jpeg',
    descriptions: 'Say hello to the Micromax IN 1b smartphone whose powerful MediaTek Helio G35 gaming processor and a 5000 mAh battery will pave the way for effortless multitasking and usage. Oh, and it also comes with the Face Unlock feature and a fingerprint sensor so that you can access your phone in a safe and secure manner.',
    brand: 'Micromax',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
      {
    _id: '3',
    name: 'CANNON EOS 80D DSLR CAMERA',
    image: '/images/camera.jpeg',
    descriptions: ' Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'CANNON',
    category: 'Electronics',
    price: 929.99,
    countInStock: 67,
    rating: 3.5,
    numReviews: 109,
  },
        {
    _id: '4',
    name: 'SONY PLAYSTATION 4 PRO WHITE VERSION',
    image: '/images/playstation.jpeg',
    descriptions: 'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'SONY',
    category: 'Electronics',
    price: 399.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 86,
  },
          {
    _id: '5',
    name: 'AMAZON ECHO DOT 3RD GENERATION',
    image: '/images/alexa.jpeg',
    descriptions: 'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 56,
    rating: 3.8,
    numReviews: 92,
  },
            {
    _id: '6',
    name: 'LOGITECH G-SERIES GAMING MOUSE',
    image: '/images/mouse.jpeg',
    descriptions: 'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech LIGHTSYNC',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 68,
  },
]

export default products